### PR TITLE
Networks course upgradation

### PR DESCRIPTION
**Pull request by reg1reg1**
This change has been made for R1 . The R1 image needs to be rebased and tested whether it worked.

### CODE REVIEW

**Comment by reg1reg1** [comment]
Once the change is tested on R1 by seeing it works , it will be merged and closed. Then the other images it will be changed.

**Comment by treddington** [comment]
List changes

**Comment by reg1reg1** [comment]
@treddington These changes are mentioned under vital architecture issue
https://github.com/vital2/Vital-Architecture/issues/1

**Comment by reg1reg1** [comment]
You can also check the changes in the commit history

**Comment by treddington** [comment]
Ok

**Comment by reg1reg1** [comment]
@treddington Merging the pull request.

**Pull request merged**
